#!/bin/sh
# Quickly make the final report pdf. Requires texlive-core & texlive-science
# packages from the arch repository.
pdflatex final.tex > /dev/null
pdftotext final.pdf
echo "Word count:"
wc -w final.txt
